import "./globals.css";
import { Heebo } from "next/font/google";
import style from "./layoute.module.scss";
import SideBar from "@/components/sidebar/SideBar";
import { getChatsByUserService } from "@/services/user.services";

const heebo = Heebo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Global S1",
  description: "Generated by Global S1",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userChats = await getChatsByUserService("646ee1e7c3fefcd38abfd81b");
  return (
    <html lang="en">
      <body className={heebo.className}>
        <div className={style.wrapper}>
          <SideBar userChats={userChats.json.content} />
          {children}
        </div>
      </body>
    </html>
  );
}
